apiVersion: v1
kind: Namespace
metadata:
  name: exam-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: exam-network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: nginx:1.29-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payments-svc
  namespace: exam-network
spec:
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 80
